In [1]:
import torch
import torch.nn as nn
torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 3060 Laptop GPU'

In [5]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [6]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [7]:
x.device

device(type='cuda', index=0)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1,2,3],device=device)
x = torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
y = x**2
y


tensor([1, 4, 9], device='cuda:0')

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。

In [10]:
net = nn.Linear(3,1)
list(net.parameters())[0].device

device(type='cpu')

In [11]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [12]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.1314],
        [-0.1348]], device='cuda:0', grad_fn=<AddmmBackward0>)