In [1]:
%matplotlib inline
import torch
from IPython import display
from matplotlib import pyplot as plt
import numpy as np
import random

In [2]:
num_inputs = 2
num_expamples = 1000
true_w = [2,-3.4]
true_b = 4.2
features = torch.randn(num_expamples,num_inputs,dtype=torch.float32)
labels = true_w[0]*features[:,0] + true_w[1]*features[:,1]+true_b
labels

tensor([ 6.5455e+00,  2.8511e+00,  6.1102e+00,  2.7343e+00,  4.3353e+00,
         8.3869e+00, -1.9383e+00,  9.6830e-01,  5.2293e+00,  1.0743e+01,
         1.0704e+01,  8.1165e+00,  9.2569e+00, -4.0949e+00,  1.6091e+00,
         2.1032e+00,  1.8585e+00,  1.5646e+01, -6.6322e-02,  6.7113e+00,
         3.9397e+00,  9.3630e+00,  8.1226e+00, -3.4625e-01,  5.8691e+00,
        -7.2654e+00,  3.9668e-01,  3.3983e+00,  5.1446e+00,  6.3692e+00,
        -9.2012e-01,  4.3290e+00,  7.8661e+00, -2.7134e+00,  9.0764e+00,
         1.2661e+01, -1.1065e+00,  7.5209e+00,  2.9910e-01,  1.2808e+00,
        -2.9027e+00,  1.5482e-01,  1.5426e+01,  1.1013e+01, -4.6445e+00,
         4.9260e-02,  2.3617e+00,  4.4320e+00,  4.6518e-01,  2.7490e+00,
         3.2716e+00,  3.9142e+00,  8.3514e+00,  2.1374e-01,  1.0372e+00,
         5.2995e+00,  3.2161e+00,  4.5029e+00,  3.1950e+00,  2.5000e+00,
         3.5663e+00,  3.8578e+00, -1.1952e+00, -2.8162e+00,  1.7818e+00,
        -6.8955e-01,  7.0222e+00,  3.9572e+00,  8.6

In [3]:
labels.shape

torch.Size([1000])

In [4]:
labels += torch.tensor(np.random.normal(0,0.01,size=labels.size()),dtype=torch.float32)

In [5]:
labels

tensor([ 6.5370e+00,  2.8525e+00,  6.1104e+00,  2.7377e+00,  4.3457e+00,
         8.4043e+00, -1.9290e+00,  9.7850e-01,  5.2290e+00,  1.0722e+01,
         1.0704e+01,  8.1255e+00,  9.2597e+00, -4.1082e+00,  1.6231e+00,
         2.1112e+00,  1.8594e+00,  1.5640e+01, -7.7707e-02,  6.7045e+00,
         3.9449e+00,  9.3706e+00,  8.1333e+00, -3.4152e-01,  5.8817e+00,
        -7.2655e+00,  3.9830e-01,  3.3970e+00,  5.1611e+00,  6.3644e+00,
        -9.1680e-01,  4.3372e+00,  7.8586e+00, -2.7227e+00,  9.0865e+00,
         1.2671e+01, -1.1035e+00,  7.5302e+00,  3.1529e-01,  1.2911e+00,
        -2.9236e+00,  1.7992e-01,  1.5433e+01,  1.1007e+01, -4.6538e+00,
         5.6812e-02,  2.3634e+00,  4.4271e+00,  4.7316e-01,  2.7568e+00,
         3.2666e+00,  3.9173e+00,  8.3527e+00,  1.9840e-01,  1.0477e+00,
         5.3226e+00,  3.2027e+00,  4.4913e+00,  3.2001e+00,  2.5031e+00,
         3.5627e+00,  3.8518e+00, -1.1988e+00, -2.8241e+00,  1.7872e+00,
        -6.9503e-01,  7.0184e+00,  3.9741e+00,  8.6

In [6]:
#加载数据
def data_iter(batch_size,features,labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)  # 样本的读取顺序是随机的
    for i in range(0, num_examples, batch_size):
        j = torch.LongTensor(indices[i: min(i + batch_size, num_examples)]) # 最后一次可能不足一个batch
        yield  features.index_select(0, j), labels.index_select(0, j)


In [7]:
batch_size = 10

for X, y in data_iter(batch_size, features, labels):
    print(X, y)
    break

tensor([[-0.5826,  0.8471],
        [ 0.3268,  1.9415],
        [ 1.0807, -1.3545],
        [-2.2392,  0.2419],
        [-2.1145, -0.5282],
        [ 0.5287,  0.1261],
        [ 1.4517, -1.4984],
        [ 0.0592, -0.8629],
        [-0.3108,  0.5948],
        [-0.9951, -0.7183]]) tensor([ 0.1799, -1.7511, 10.9521, -1.1010,  1.7690,  4.8394, 12.1992,  7.2557,
         1.5552,  4.6515])


In [8]:
w = torch.tensor((np.random.normal(0,0.01,(num_inputs,1))),dtype=torch.float32)

In [10]:
b = torch.zeros(1,dtype=torch.float32)
w.requires_grad_(True)

tensor([[0.0072],
        [0.0030]], requires_grad=True)

In [11]:
b.requires_grad_(True)

tensor([0.], requires_grad=True)

In [12]:
def linreg(X,w,b):
    return torch.mm(X,w)+b

In [13]:
def squared_loss(y_hat, y):  # 本函数已保存在d2lzh_pytorch包中方便以后使用
    # 注意这里返回的是向量, 另外, pytorch里的MSELoss并没有除以 2
    return (y_hat - y.view(y_hat.size())) ** 2 / 2

In [14]:
def sgd(params, lr, batch_size):  # 本函数已保存在d2lzh_pytorch包中方便以后使用
    for param in params:
        param.data -= lr * param.grad / batch_size # 注意这里更改param时用的param.data

In [15]:
lr = 0.03
num_epochs = 3
net = linreg
loss = squared_loss

for epoch in range(num_epochs):  # 训练模型一共需要num_epochs个迭代周期
    # 在每一个迭代周期中，会使用训练数据集中所有样本一次（假设样本数能够被批量大小整除）。X
    # 和y分别是小批量样本的特征和标签
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X, w, b), y).sum()  # l是有关小批量X和y的损失
        l.backward()  # 小批量的损失对模型参数求梯度
        sgd([w, b], lr, batch_size)  # 使用小批量随机梯度下降迭代模型参数

        # 不要忘了梯度清零
        w.grad.data.zero_()
        b.grad.data.zero_()
    train_l = loss(net(features, w, b), labels)
    print('epoch %d, loss %f' % (epoch + 1, train_l.mean().item()))

epoch 1, loss 0.039318
epoch 2, loss 0.000148
epoch 3, loss 0.000051


In [16]:
print(true_w, '\n', w)
print(true_b, '\n', b)

[2, -3.4] 
 tensor([[ 2.0006],
        [-3.4005]], requires_grad=True)
4.2 
 tensor([4.1992], requires_grad=True)
